/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontera;

import control.InsertCell;
import control.InsertPlan;
import entidad.cell;
import static frontera.IncludeCell.modelCell;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Diego
 */
public class CatalogoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CatalogoPanel
     */
    //cell c;
    cell c = new cell();
    private Object objcell;

    
    
    public CatalogoPanel() {
        //try {
             initComponents();
             //mostrarClelulares();
             jListCells.setModel(frontera.IncludeCell.modelCell); //actualiza la lista de cell
            
             //jComboBox1.addActionListener(jComboBox1);
             //jList1.setModel(modelCell);
             
             
             
             /*
             Bloque sin comentar muestra los celulares desde cells.db
             
                //initComponents();
                InsertCell celulares = new InsertCell();
                ArrayList<String> nameCells = celulares.returnNameCell();
                
                DefaultListModel modelo = new DefaultListModel();
                jListCells.setModel(modelo);
                modelo.addElement(nameCells);
                
                modelo.removeAllElements();
                for (int i = 0; i < nameCells.size(); i++) {
                    modelo.addElement(nameCells.get(i));
                }
            */
             
             
             /*
             InsertCell ic = new InsertCell();
             ArrayList<String[]> cells = ic.returnCellss();
             String nameCell = ic.returnNameCell();
             
             for(int i=0;i<cells.get(0).length;i++){
                 model.addElement(cells.get(0)[i]);
             }
             */
             
             //this.jList4.setModel(model);
             //this.model.addElement(objcell);
             //this.nameCells.setName("nameCell");
             //jList1.setModel(modelCell);
        // } catch (IOException ex) {
          //   Logger.getLogger(PlanesPanel.class.getName()).log(Level.SEVERE, null, ex);
        // }
    }
    
    public void mostrarClelulares ()
    {
      
      int i=0;
     
        for ( i = 0; i <frontera.Pantalla_principal.listaCell.size(); i++) 
        {
            //jComboBox1.addItem(frontera.Pantalla_principal.listaCell.get(i).getCompany());
            //jComboBox1.addItem(frontera.IncludeCell.modelCell.get(i).toString());
            //jList1.addKeyListener(frontera.IncludeCell.modelCell.get(i).toString());
            //frontera.Pantalla_principal.listaCell.add(c)
            //modelCell.addElement(frontera.Pantalla_principal.listaCell.get(i).getCompany());
            //modelCell.addElement(objcell);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        company = new javax.swing.JLabel();
        processor = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        rom = new javax.swing.JLabel();
        camera = new javax.swing.JLabel();
        batery = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        plan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCells = new javax.swing.JList<>();
        jBShowCell = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList3);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Imagen");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jInternalFrame2.setVisible(true);

        company.setText("company :");
        company.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                companyAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        processor.setText("processor :");

        ram.setText("ram :");

        rom.setText("rom :");

        camera.setText("camera :");

        batery.setText("batery :");

        cost.setText("cost :");

        plan.setText("plan :");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(company)
                    .addComponent(processor)
                    .addComponent(ram)
                    .addComponent(rom)
                    .addComponent(camera)
                    .addComponent(batery)
                    .addComponent(cost)
                    .addComponent(plan))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(company)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plan)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jListCells.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCells);

        jBShowCell.setText("Show Cell");
        jBShowCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBShowCellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBShowCell))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBShowCell, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1)
                    .addComponent(jInternalFrame2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void companyAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_companyAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_companyAncestorAdded

    private void jBShowCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBShowCellActionPerformed
        // TODO add your handling code here:
        int index= jListCells.getSelectedIndex();
        
        company.setText("company: "+ frontera.Pantalla_principal.listaCell.get(index).getCompany());
        processor.setText("procesor: "+ frontera.Pantalla_principal.listaCell.get(index).getProcessor());
        ram.setText("ram: "+ frontera.Pantalla_principal.listaCell.get(index).getRam());
        rom.setText("rom: "+ frontera.Pantalla_principal.listaCell.get(index).getRom());
        camera.setText("camera: "+ frontera.Pantalla_principal.listaCell.get(index).getCamera());
        batery.setText("batery: "+ frontera.Pantalla_principal.listaCell.get(index).getBatery());
        cost.setText("cost: "+ frontera.Pantalla_principal.listaCell.get(index).getCost());
        plan.setText("plan: "+ frontera.Pantalla_principal.listaCell.get(index).isPlan());
        
    }//GEN-LAST:event_jBShowCellActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batery;
    private javax.swing.JLabel camera;
    private javax.swing.JLabel company;
    private javax.swing.JLabel cost;
    private javax.swing.JButton jBShowCell;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jListCells;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel plan;
    private javax.swing.JLabel processor;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel rom;
    // End of variables declaration//GEN-END:variables

}
