/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontera;

import dao.cellDAO;
import entidad.cell;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import frontera.IncludeCell;
import java.awt.Color;
import java.awt.PopupMenu;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import org.jdesktop.beansbinding.ELProperty;
/**
 *
 * @author JULIO
 */
public class CompararPanel extends javax.swing.JPanel  {

    /**
     * Creates new form CompararPanel
     */
    
   
    
    public CompararPanel()   {
        
        initComponents();
        cellDAO aux = new cellDAO();
        cell par = new cell();
        //jListFirstCell.add(aux.leer()); 
        modelo();
        jListFirstCell.setModel(frontera.IncludeCell.modelCell); 
        jListSecondCell.setModel(frontera.IncludeCell.modelCell); //actualiza la lista de cell
        
        //mostrarCelulares();
        //PrimerCell.addActionListener(PrimerCell);
        //SegundoCell.addActionListener(SegundoCell);
       
    }
    
    
    
   public void modelo()
   {    initComponents();
       DefaultListModel modelo = new DefaultListModel();
       for (int i = 0; i < frontera.Pantalla_principal.listaCell.size(); i++) {
           modelo.addElement(frontera.Pantalla_principal.listaCell.get(i).getCompany());
           System.out.println(" lo del for "+frontera.Pantalla_principal.listaCell.get(i).getCompany());
       }
       jListFirstCell.setModel(modelo);
       jListSecondCell.setModel(modelo);
   } 
    public void mostrarCelulares ()
    {
      
      int i=0;
     
        for ( i = 0; i <frontera.Pantalla_principal.listaCell.size(); i++) 
        {
            //PrimerCell.addItem(frontera.Pantalla_principal.listaCell.get(i).getCompany());
            //SegundoCell.addItem(frontera.Pantalla_principal.listaCell.get(i).getCompany());
           
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("MB_version_8.2PU").createEntityManager();
        celularesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("Select UPPER(e.company) from cell e ");
        celularesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : celularesQuery.getResultList();
        Comapre_1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textcom1 = new javax.swing.JTextField();
        textpros1 = new javax.swing.JTextField();
        textram1 = new javax.swing.JTextField();
        textrom1 = new javax.swing.JTextField();
        textcam1 = new javax.swing.JTextField();
        textbat1 = new javax.swing.JTextField();
        textcos1 = new javax.swing.JTextField();
        textplan1 = new javax.swing.JTextField();
        Compare_2 = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textcomp2 = new javax.swing.JTextField();
        textpros2 = new javax.swing.JTextField();
        textram2 = new javax.swing.JTextField();
        textrom2 = new javax.swing.JTextField();
        textcam2 = new javax.swing.JTextField();
        textbat2 = new javax.swing.JTextField();
        textcost2 = new javax.swing.JTextField();
        textplan2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFirstCell = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSecondCell = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        actualizar = new javax.swing.JButton();

        setAutoscrolls(true);

        Comapre_1.setVisible(true);

        jLabel1.setText("company");

        jLabel2.setText("processor");

        jLabel3.setText("ram");

        jLabel4.setText("rom");

        jLabel5.setText("camara");

        jLabel6.setText("batery");

        jLabel7.setText("cost");

        jLabel8.setText("plan");

        textcom1.setEditable(false);
        textcom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcom1ActionPerformed(evt);
            }
        });

        textpros1.setEditable(false);

        textram1.setEditable(false);

        textrom1.setEditable(false);
        textrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrom1ActionPerformed(evt);
            }
        });

        textcam1.setEditable(false);

        textbat1.setEditable(false);

        textcos1.setEditable(false);

        textplan1.setEditable(false);

        javax.swing.GroupLayout Comapre_1Layout = new javax.swing.GroupLayout(Comapre_1.getContentPane());
        Comapre_1.getContentPane().setLayout(Comapre_1Layout);
        Comapre_1Layout.setHorizontalGroup(
            Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Comapre_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addComponent(textplan1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(textcos1))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addComponent(textbat1))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textpros1)
                            .addComponent(textcom1)))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(textram1))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(textrom1))
                    .addGroup(Comapre_1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16)
                        .addComponent(textcam1)))
                .addContainerGap())
        );
        Comapre_1Layout.setVerticalGroup(
            Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Comapre_1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textpros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textram1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textrom1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textcam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textbat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Comapre_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textplan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Compare_2.setVisible(true);

        jLabel9.setText("company");

        jLabel10.setText("processor");

        jLabel11.setText("ram");

        jLabel12.setText("rom");

        jLabel13.setText("camara");

        jLabel14.setText("batery");

        jLabel15.setText("cost");

        jLabel16.setText("plan");

        textcomp2.setEditable(false);
        textcomp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcomp2ActionPerformed(evt);
            }
        });

        textpros2.setEditable(false);
        textpros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpros2ActionPerformed(evt);
            }
        });

        textram2.setEditable(false);
        textram2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textram2ActionPerformed(evt);
            }
        });

        textrom2.setEditable(false);
        textrom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrom2ActionPerformed(evt);
            }
        });

        textcam2.setEditable(false);
        textcam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcam2ActionPerformed(evt);
            }
        });

        textbat2.setEditable(false);
        textbat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbat2ActionPerformed(evt);
            }
        });

        textcost2.setEditable(false);
        textcost2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcost2ActionPerformed(evt);
            }
        });

        textplan2.setEditable(false);
        textplan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textplan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Compare_2Layout = new javax.swing.GroupLayout(Compare_2.getContentPane());
        Compare_2.getContentPane().setLayout(Compare_2Layout);
        Compare_2Layout.setHorizontalGroup(
            Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Compare_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textram2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textbat2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textcost2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textplan2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Compare_2Layout.createSequentialGroup()
                                .addComponent(textcomp2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textpros2)))
                    .addGroup(Compare_2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(textcam2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Compare_2Layout.setVerticalGroup(
            Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Compare_2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textcomp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textpros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textram2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textrom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textcam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(textbat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(textcost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Compare_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textplan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setText("comparar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jListFirstCell.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, celularesQuery, org.jdesktop.beansbinding.ELProperty.create("${resultList}"), jListFirstCell, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jListFirstCell.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jListFirstCellComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jListFirstCell);

        jListSecondCell.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, celularesQuery, eLProperty, jListSecondCell);
        bindingGroup.addBinding(jListBinding);

        jScrollPane2.setViewportView(jListSecondCell);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, celularesQuery, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);

        actualizar.setText("actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Comapre_1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(Compare_2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(actualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Compare_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comapre_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void textcom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcom1ActionPerformed

    private void textcomp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcomp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcomp2ActionPerformed

    private void textpros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpros2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpros2ActionPerformed

    private void textram2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textram2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textram2ActionPerformed

    private void textrom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrom2ActionPerformed

    private void textcam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcam2ActionPerformed

    private void textbat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbat2ActionPerformed

    private void textcost2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcost2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcost2ActionPerformed

    private void textplan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textplan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textplan2ActionPerformed

    private void textrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrom1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // datos del primer celular 
        int i;
        i= jListFirstCell.getSelectedIndex();
        int j;
        j=jListSecondCell.getSelectedIndex();
        System.out.println(i +"   "+ j);
        
        //compañia
        textcom1.setText(frontera.Pantalla_principal.listaCell.get(i).getCompany());
        //precesador
        textpros1.setText(frontera.Pantalla_principal.listaCell.get(i).getProcessor());
        //ram
        String Rma = Double.toString(frontera.Pantalla_principal.listaCell.get(i).getRam());
        textram1.setText(Rma);
        //rom
        String Rmo = Double.toString(frontera.Pantalla_principal.listaCell.get(i).getRom());
        textrom1.setText(Rmo);
        //camara
        String Cam = Double.toString(frontera.Pantalla_principal.listaCell.get(i).getCamera());
        textcam1.setText(Cam);
        //batery
        String Bat = Double.toString(frontera.Pantalla_principal.listaCell.get(i).getBatery());
        textbat1.setText(Bat);
         //cost
        String Cst = Double.toString(frontera.Pantalla_principal.listaCell.get(i).getCost());
        textcos1.setText(Cst);
        //plan
        String Pln = Boolean.toString(frontera.Pantalla_principal.listaCell.get(i).isPlan());
        textplan1.setText(Pln);
        
        // datos del segundo celular
        //company 
        textcomp2.setText(frontera.Pantalla_principal.listaCell.get(j).getCompany());
        //prosesador 
        textpros2.setText(frontera.Pantalla_principal.listaCell.get(j).getProcessor());
        //ram
        String Rma2 = Double.toString(frontera.Pantalla_principal.listaCell.get(j).getRam());
        textram2.setText(Rma2);
        //rom
         String Rmo1 = Double.toString(frontera.Pantalla_principal.listaCell.get(j).getRom());
         textrom2.setText(Rmo1);
         //camara
        String Cam1 = Double.toString(frontera.Pantalla_principal.listaCell.get(j).getCamera());
        textcam2.setText(Cam1);
        //bateria
        String Bat1 = Double.toString(frontera.Pantalla_principal.listaCell.get(j).getBatery());
        textbat2.setText(Bat1);
        //cost
        String Cst1 = Double.toString(frontera.Pantalla_principal.listaCell.get(j).getCost());
        textcost2.setText(Cst1);
        //plan 
        String Pln1 = Boolean.toString(frontera.Pantalla_principal.listaCell.get(j).isPlan());
        textplan2.setText(Pln1);

        
        
        String resultado = new String();
        resultado=control.comparar.compararc(i,j);
        
        comparar(resultado);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListFirstCellComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jListFirstCellComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jListFirstCellComponentAdded

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, celularesQuery, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        jComboBox1.add((PopupMenu) celularesQuery);

    }//GEN-LAST:event_actualizarActionPerformed

    private void comparar(String resultados)
    {   char opcion;
        
        for (int i = 0; i < 5; i++) 
        {
            switch(i){    
                case 0:
                opcion = resultados.charAt(i);
                if(opcion == '1')
                {
                    textram1.setBackground(Color.red);
                    textram2.setBackground(Color.GREEN);
            
                }else if(opcion == '2')
                {
                    textram1.setBackground(Color.red);
                    textram2.setBackground(Color.GREEN);
            
                }else
                {
                    textram1.setBackground(Color.yellow);
                    textram2.setBackground(Color.yellow);
                }
                break;
                
                case 1:
                opcion = resultados.charAt(i);
                if(opcion == '1')
                {
                    textrom1.setBackground(Color.red);
                    textrom2.setBackground(Color.GREEN);
            
                }else if(opcion == '2')
                {

                    textrom2.setBackground(Color.red);
                    textrom1.setBackground(Color.GREEN);

                }else
                {

                    textrom1.setBackground(Color.yellow);
                    textrom2.setBackground(Color.yellow);
        
                }
                break;
                
                case 2:
                opcion = resultados.charAt(i);
                if(opcion == '1')
                {

                    textcam1.setBackground(Color.red);
                    textcam2.setBackground(Color.GREEN);
         
                }else if(opcion == '2')
                {

                    textcam2.setBackground(Color.red);
                    textcam1.setBackground(Color.GREEN);

                }else
                {
                    
                    textcam1.setBackground(Color.yellow);
                    textcam2.setBackground(Color.yellow);

                }
                break;
                
                case 3:
                opcion = resultados.charAt(i);
                if(opcion == '1')
                {

                    textbat1.setBackground(Color.red);
                    textbat2.setBackground(Color.GREEN);
         
                }else if(opcion == '2')
                {

                    textbat2.setBackground(Color.red);
                    textbat1.setBackground(Color.GREEN);
           
                }else
                {

                    textbat1.setBackground(Color.yellow);
                    textbat2.setBackground(Color.yellow);

                }
                break;
                
                case 4:
                opcion = resultados.charAt(i);
                if(opcion == '1')
                {

                    textcost2.setBackground(Color.GREEN);
                    textcos1.setBackground(Color.red);
         
                }else if(opcion == '2')
                {
                    
                    textcos1.setBackground(Color.GREEN);
                    textcost2.setBackground(Color.red);

                }else
                {

                    textcos1.setBackground(Color.yellow);
                    textcost2.setBackground(Color.yellow);
        
                }
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Comapre_1;
    private javax.swing.JInternalFrame Compare_2;
    private javax.swing.JButton actualizar;
    private java.util.List<frontera.Celulares> celularesList;
    private javax.persistence.Query celularesQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListFirstCell;
    private javax.swing.JList<String> jListSecondCell;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField textbat1;
    private javax.swing.JTextField textbat2;
    private javax.swing.JTextField textcam1;
    private javax.swing.JTextField textcam2;
    private javax.swing.JTextField textcom1;
    private javax.swing.JTextField textcomp2;
    private javax.swing.JTextField textcos1;
    private javax.swing.JTextField textcost2;
    private javax.swing.JTextField textplan1;
    private javax.swing.JTextField textplan2;
    private javax.swing.JTextField textpros1;
    private javax.swing.JTextField textpros2;
    private javax.swing.JTextField textram1;
    private javax.swing.JTextField textram2;
    private javax.swing.JTextField textrom1;
    private javax.swing.JTextField textrom2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
