/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontera;

import entidad.cell;
//import static frontera.IncludeCell.modelCell;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author BRIAN
 */
public class EditCell extends javax.swing.JPanel {

    /**
     * Creates new form Plan
     */
    
    public EditCell() {
        initComponents();
        jListCells.setModel(frontera.IncludeCell.modelCell);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        DataPlanPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jEditCell = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCells = new javax.swing.JList<>();
        jButtonRemoveCell = new javax.swing.JButton();
        jLCompany = new javax.swing.JLabel();
        jLProcessor = new javax.swing.JLabel();
        jLRam = new javax.swing.JLabel();
        jLRom = new javax.swing.JLabel();
        jLCamera = new javax.swing.JLabel();
        jLBatery = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCompany = new javax.swing.JTextField();
        jProcessor = new javax.swing.JTextField();
        jRam = new javax.swing.JTextField();
        jRom = new javax.swing.JTextField();
        jCamera = new javax.swing.JTextField();
        jBatery = new javax.swing.JTextField();
        jCost = new javax.swing.JTextField();
        jPlan = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();

        javax.swing.GroupLayout DataPlanPanelLayout = new javax.swing.GroupLayout(DataPlanPanel);
        DataPlanPanel.setLayout(DataPlanPanelLayout);
        DataPlanPanelLayout.setHorizontalGroup(
            DataPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        DataPlanPanelLayout.setVerticalGroup(
            DataPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("EDIT CELLPHONE");

        jEditCell.setText("Edit cell");
        jEditCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditCellActionPerformed(evt);
            }
        });

        jLabel5.setText("Please, select the equipment to be modified");

        jListCells.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CellPhone 1", "CellPhone 2", "CellPhone 3", "CellPhone 4", "CellPhone 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCells.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jListCellsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jListCells);

        jButtonRemoveCell.setText("Remove");
        jButtonRemoveCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveCellActionPerformed(evt);
            }
        });

        jLCompany.setText("Company: ");

        jLProcessor.setText("Processor: ");

        jLRam.setText("Ram: ");

        jLRom.setText("Rom: ");

        jLCamera.setText("Camera: ");

        jLBatery.setText("Batery: ");

        jLabel2.setText("Cost:");

        jLabel3.setText("Plan: ");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEditCell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveCell))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLCompany)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLProcessor)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jLRam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLRom, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLCamera, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLBatery, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSave)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCamera, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jRam)
                                        .addComponent(jRom)
                                        .addComponent(jBatery)
                                        .addComponent(jCost)
                                        .addComponent(jPlan)
                                        .addComponent(jProcessor))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DataPlanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCompany)
                            .addComponent(jCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLProcessor)
                            .addComponent(jProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLRam))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRom)
                            .addComponent(jRom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCamera)
                            .addComponent(jCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLBatery)
                            .addComponent(jBatery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditCell)
                    .addComponent(jButtonRemoveCell))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(DataPlanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 341, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEditCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditCellActionPerformed
        // TODO add your handling code here:
        int index = jListCells.getSelectedIndex();
        
        jCompany.setText(frontera.Pantalla_principal.listaCell.get(index).getCompany());
        jProcessor.setText(frontera.Pantalla_principal.listaCell.get(index).getProcessor());
        
        String Ram = Double.toString(frontera.Pantalla_principal.listaCell.get(index).getRam());
        jRam.setText(Ram);
        
        String Rom = Double.toString(frontera.Pantalla_principal.listaCell.get(index).getRom());
        jRom.setText(Rom);
        
        String Camera = Double.toString(frontera.Pantalla_principal.listaCell.get(index).getCamera());
        jCamera.setText(Camera);
        
        String Batery = Double.toString(frontera.Pantalla_principal.listaCell.get(index).getBatery());
        jBatery.setText(Batery);
        
        String Cost = Double.toString(frontera.Pantalla_principal.listaCell.get(index).getCost());
        jCost.setText(Cost);
        
        String Plan = Boolean.toString(frontera.Pantalla_principal.listaCell.get(index).isPlan());
        jPlan.setText(Plan);
        
    }//GEN-LAST:event_jEditCellActionPerformed

    private void jListCellsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListCellsAncestorAdded
        //String company ,processor,ram,rom,camera,batery,cost,plan = " ";
        //cell objcell = new cell(company, processor, ram, rom, camera, batery, cost, plan);
        //modelCell.addElement(objcell);
    }//GEN-LAST:event_jListCellsAncestorAdded

    private void jButtonRemoveCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveCellActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jListCells.getModel(); 
        int index = jListCells.getSelectedIndex();
        modelo.remove(index);
        frontera.Pantalla_principal.listaCell.remove(index);
    }//GEN-LAST:event_jButtonRemoveCellActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int index = jListCells.getSelectedIndex();
        
        String company = jCompany.getText();
        String processor = jProcessor.getText();
        String cost = jCost.getText();
        String batery = jBatery.getText();
        String camera = jCamera.getText();
        String ram = jRam.getText();
        String rom = jRom.getText();
        String plan = jPlan.getText();
        
        if(cost.isEmpty() || company.isEmpty() || processor.isEmpty() || batery.isEmpty()
              || camera.isEmpty() || ram.isEmpty() || rom.isEmpty() || plan.isEmpty()){
          JOptionPane.showMessageDialog(null, "Error de ingreso:\n"
                    + "Por favor ingrese todos los datos solicitados", "Información incompleta",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                
                cell objcell = new cell(company, processor, Double.parseDouble(ram),
                        Double.parseDouble(rom), Double.parseDouble(camera),
                        Double.parseDouble(batery), Double.parseDouble(cost),
                        Boolean.getBoolean(plan));
                //modelCell.addElement(objcell);
                //frontera.Pantalla_principal.listaCell.add(objcell);
                frontera.Pantalla_principal.listaCell.set(index, objcell);
                
            } catch (NumberFormatException ex) {
                Logger.getLogger(IncludePlan.class.getName()).log(Level.SEVERE, null, ex);
            }
          JOptionPane.showMessageDialog(null, "Se ha editado correctamente el Celular",   "Correcto",
                    JOptionPane.INFORMATION_MESSAGE);
                    
                    DataPlanPanel.setVisible(true);
                    //DataPlanPanel.removeAll();
                    //DataPlanPanel.add(Cost);
                    //DataPlanPanel.setVisible(true);
                    
        this.jCost.setText("");
        this.jCompany.setText("");
        this.jProcessor.setText("");
        this.jBatery.setText("");
        this.jCamera.setText("");
        this.jRam.setText("");
        this.jRom.setText("");
        this.jPlan.setText("");
    }
    }//GEN-LAST:event_jButtonSaveActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPlanPanel;
    private javax.swing.JTextField jBatery;
    private javax.swing.JButton jButtonRemoveCell;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JTextField jCamera;
    private javax.swing.JTextField jCompany;
    private javax.swing.JTextField jCost;
    private javax.swing.JButton jEditCell;
    private javax.swing.JLabel jLBatery;
    private javax.swing.JLabel jLCamera;
    private javax.swing.JLabel jLCompany;
    private javax.swing.JLabel jLProcessor;
    private javax.swing.JLabel jLRam;
    private javax.swing.JLabel jLRom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListCells;
    private javax.swing.JTextField jPlan;
    private javax.swing.JTextField jProcessor;
    private javax.swing.JTextField jRam;
    private javax.swing.JTextField jRom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
